/* eslint-disable @next/next/no-html-link-for-pages */
const work = [
  { slug: "8agents", name: "8Agents", category: "AI Product", status: "Building", logo: "/logos/8agents-128.webp", summary: "A structured platform for learning, designing, and developing AI agents.", liveUrl: "https://8agents.xyz" },
  { slug: "8router", name: "8Router", category: "Developer Tool", status: "Beta / Active Development", logo: "/logos/8router-mark.svg", summary: "An OpenAI-compatible gateway for routing, fallback, credentials, and multi-provider AI access.", liveUrl: "https://8router.8agents.xyz" },
  { slug: "nihongogate", name: "NihongoGate", category: "Education Product", status: "Active Development", logo: "/logos/nihongogate-64.svg", summary: "A Japanese and SSW learning platform built around practical learning workflows.", liveUrl: "https://nihongogate.kaidevlab.com" },
  { slug: "rakusaku", name: "Rakusaku", category: "Digital Commerce Prototype", status: "Prototype — Payment Integration Pending", logo: "/logos/rakusaku-128.webp", summary: "A game top-up prototype exploring commerce architecture and playful branding.", liveUrl: "https://rakusaku.com" },
  { slug: "kai-revengers", name: "Kai Revengers", category: "Video Content Project", status: "Series in Production", logo: "/logos/kai-revengers-64.svg", poster: "/kai-revengers-poster.jpg", summary: "An anime-inspired video content project built around rivalry arcs and cinematic short-form storytelling." },
  { slug: "dragon-kings-last-contract", name: "The Dragon King’s Last Contract", category: "AI Film Series", status: "Series in Production", logo: "/logos/kai-revengers-64.svg", poster: "/dragon-kings-last-contract-poster.jpg", summary: "A dark fantasy film series built with Seedance 2.0 workflows." },
];

export default function Work(){return <main className="section"><p className="eyebrow">WORK</p><h1>Products, AI systems, developer tools, education, creative experiments.</h1><p>Filters: All · Products · AI Systems · Developer Tools · Education · Creative · Experiments</p><div className="project-grid">{work.map(({slug,name,category,status,logo,poster,summary,liveUrl})=><article className={`project ${poster ? "creative-card" : ""}`} key={name}><div className={`thumb project-visual ${poster ? "poster-visual" : ""}`}>{poster && <img className="poster-bg" src={poster} alt="" aria-hidden="true"/>}<div className="visual-grid" aria-hidden="true"/>{!poster && <img src={logo} alt="" aria-hidden="true"/>}<div className="visual-lines" aria-hidden="true"><span/><span/><span/></div><strong>{name}</strong></div><p className="chip">{category}</p><h3>{name}</h3><p>{summary}</p><p className="status">{status}</p><div className="project-actions"><a href={`/work/${slug}`}>View Project</a>{liveUrl && <a href={liveUrl} target="_blank" rel="noreferrer">Live Site</a>}</div></article>)}</div><a className="secondary" href="/">Back Home</a></main>}